version: "3.11"

services:
  install:
    build:
      context: .
    container_name: blog_install
    volumes:
      - .:/var/www/html
    command: "composer install"

  blog:
    build:
      context: deployment/docker/web
    container_name: blog
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql

  #---------------------------------
  # Storage
  #---------------------------------
  mysql:
    image: mysql:8-oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog

  redis:
    image: redis/redis-stack-server:6.2.2-v1
    volumes:
      - redis:/var/lib/redis

volumes:
  mysql:
    driver: local
  redis:
    driver: local

